### ISSUE TITLE
Can't get it to work with ESP8266 controller

### ISSUE THREAD

**Issue by stoehrmark** [jnimmo/hass-artnet#16]
I have an ESP8266 based DMX Art-Net controller [ESP8266_ArtNetNode_v2](https://github.com/mtongnz/ESP8266_ArtNetNode_v2)
Works great with FreeStyler but can't get it to work with hass-artnet
HA is not showing any errors just not controlling the light.
The test light is a [The Puck](https://www.soundpro.com/catalog/documents/the-puck-rgb-cp-user-manual-rev-a.pdf)
I tried the following config
 light 99:
   - platform: artnet
     host: 10.10.45.141 //IP of the ESP8266
     # port: 6454
     dmx_channels: 512 
     default_level: 0
     devices:
       - channel: 1
         type: drgb
         name: DMX_Entrance LED Strip
         default_rgb: [0,0,0]
         default_level: 0

Any help would be great
Thanks in advance and great work

**Comment by stoehrmark** [comment]
Strange that the forum made "port: 6454" larger and bold. This was not intended.

**Comment by TimothyLeeAdams** [comment]
Might try moving the light you are trying to control to DMX channel 3 and see if it receives DMX. I found that 'artnet.py' has a bug that prevents it from outputting on channels 1 + 2.

**Comment by stoehrmark** [comment]
No luck. I tried many channels 3 and above.  In the ESP8266 software there are options for the following maybe I need to change these?  As they are they work in FreeStyler

![artnetesp8266](https://user-images.githubusercontent.com/24501941/49942816-5e08bf00-feb4-11e8-857c-002e7ca101df.jpg)

**Comment by stoehrmark** [comment]
I'm a dummy. Universe 0 Working now

**Comment by jnimmo** [comment]
Glad you got it sorted!
